blank_issues_enabled : false
contact_links : 
  - name : Ask a Question
    url : https://github.com/akashsonowal/interpolating-neural-networks/discussions/new
    about : Ask and Answer Question related to Interpolating Neural Networks 
